services:
  web:
    build: ./medguardian
    image: 818271266998.dkr.ecr.us-east-1.amazonaws.com/medguardian:medguardian_web
    command: gunicorn medguardian.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./medguardian:/usr/src/medguardian/
      - static_volume:/home/medguardian/web/staticfiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    environment:
      - DB_NAME=medguardian_db
      - DB_USER=postgres
      - DB_PASSWORD=REMOVED
      - DB_HOST=medguardian.c7zbj5g2txwt.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-50-16-207-76.compute-1.amazonaws.com
      - VIRTUAL_PORT=2813
    entrypoint: /entrypoint.sh
    # depends_on:
    #   - pg
    # pg:
    #   container_name: pg_container
    #   image: postgres:14.4-alpine3.16
    #   restart: always
    #   environment:
    #     POSTGRES_USER: postgres
    #     POSTGRES_PASSWORD: REMOVED
    #     POSTGRES_DB: medguardian_db
    #     POSTGRES_HOST_AUTH_METHOD: trust
    #   ports:
    #     - "5432:5432"
    #   volumes:
    #     - ./data:/data
    #     - ./data/misc/medguardian_db_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
    # pgadmin:
    #   container_name: pgadmin_container
    #   image: dpage/pgadmin4:6.11
    #   restart: always
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: admin@example.com
    #     PGADMIN_DEFAULT_PASSWORD: REMOVED
    #     PGADMIN_LISTEN_PORT: 5433
    #     PGADMIN_CONFIG_SERVER_MODE: "False"
    #     PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    #   ports:
    #     - "5433:5433"
    #   depends_on:
    #     - pg
  notification_service:
    build: ./services
    image: 818271266998.dkr.ecr.us-east-1.amazonaws.com/medguardian:medguardian_notification_service
    command: python med_notification.py
    expose:
      - 8002
    environment:
      - DB_NAME=medguardian_db
      - DB_USER=postgres
      - DB_PASSWORD=REMOVED
      - DB_HOST=medguardian.c7zbj5g2txwt.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-50-16-207-76.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
    depends_on:
      - web
  db_load:
    build: ./services
    image: 818271266998.dkr.ecr.us-east-1.amazonaws.com/medguardian:medguardian_db_load
    command: python update_db.py
    expose:
      - 8003
    environment:
      - DB_NAME=medguardian_db
      - DB_USER=postgres
      - DB_PASSWORD=REMOVED
      - DB_HOST=medguardian.c7zbj5g2txwt.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-50-16-207-76.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
      - ADMIN_ROUTE_FILE=./data/routes.data
      - ADMIN_FREQ_FILE=./data/frequencies.data
      - MEDICATION_DATA_FILE=./data/medications.txt
    entrypoint: /entrypoint.sh
    depends_on:
      - web
  nginx:
    build: ./nginx
    image: 818271266998.dkr.ecr.us-east-1.amazonaws.com/medguardian:medguardian_nginx
    volumes:
      - static_volume:/home/medguardian/web/staticfiles
    ports:
      - 2813:80
    depends_on:
      - web

volumes:
  static_volume:
