services:
  web:
    build: ./medguardian
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./medguardian:/usr/src/medguardian/
    ports:
      - 8000:8000
    environment:
      - DB_NAME=medguardian_db
      - DB_USER=postgres
      - DB_PASSWORD=brongirl9
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - pg
  pg:
    container_name: pg_container
    image: postgres:14.4-alpine3.16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brongirl9
      POSTGRES_DB: medguardian_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/misc/medguardian_db_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.11
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: brongirl9
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg
