# Generated by Django 4.0.5 on 2022-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(help_text='The generic name of the medication', max_length=128)),
                ('brand_name', models.CharField(help_text='The brand name of the medication', max_length=128)),
                ('strength', models.FloatField(help_text='The strength per dosage unit')),
                ('manufacturer', models.CharField(help_text='The name of the manufacturer', max_length=128)),
            ],
        ),
    ]
