# Generated by Django 4.0.5 on 2022-07-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_form',
            field=models.CharField(default='tablet', help_text='The dosage form of the medication', max_length=80),
        ),
        migrations.AddField(
            model_name='medication',
            name='strength_units',
            field=models.CharField(default='mg', help_text='The units of measure for the medication strength', max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='brand_name',
            field=models.CharField(blank=True, help_text='The brand name of the medication', max_length=128),
        ),
        migrations.CreateModel(
            name='MedicationProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc', models.CharField(help_text='The National Drug Code for a medication', max_length=11)),
                ('manufacturer', models.CharField(default='', help_text='Medication products manufacturer', max_length=80)),
                ('schedule', models.PositiveSmallIntegerField(blank=True, help_text='Controlled substance category for medication', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
            ],
        ),
    ]
