# Generated by Django 4.0.5 on 2022-07-18 03:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='date_time_taken',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 3, 58, 32, 502867, tzinfo=utc), help_text='Date and time taken'),
        ),
    ]
