# Generated by Django 4.0.5 on 2022-07-18 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_administration_date_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='date_time_taken',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 4, 28, 1, 171782, tzinfo=utc), help_text='Date and time taken'),
        ),
    ]
